apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8s-manager

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: k8s-manager
  app.kubernetes.io/component: api-server
